config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  get 'about' => 'welcome#about'
  
  devise_for :users 
  
  resources :users, only: [:update, :show]

  resources :wikis do
    resources :collaborators, only: [:create, :destroy]
  end
  
  resources :charges, only: [:new, :create]
  
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
  validates_uniqueness_of :user_id, scope: [:wiki_id]

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :collaborators
  has_many :wikis, through: :collaborators

  def standard?
    role == 'standard'
  end
  
  def premium?
    role == 'premium'
  end
  
  def admin?
    role == 'admin'
  end
  
  def publicize_wikis
    Wiki.where(user: self).each do |wiki|
      if wiki.private == true
        wiki.update_attributes(private: false)
      end
    end
  end

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators
  
  default_scope { order('created_at DESC') } 
  
  scope :visible_to, ->(user) { user ? all : where(private: nil) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end
  
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

    def new
        @stripe_btn_data = {
            key: "#{ Rails.configuration.stripe[:publishable_key] }",
            description: "Membership Upgrade - #{current_user.name}",
            amount: 1500
        }
    end

    def create
        customer = Stripe::Customer.create(
            email: current_user.email,
            card: params[:stripeToken]
        )
        
        charge = Stripe::Charge.create(
            customer: customer.id,
            amount: 1500,
            description: "Membership Upgrade - #{current_user.email}",
            currency: 'usd'
        )

        if charge
            current_user.update_attributes(role: "premium")
            flash[:notice] = "Thank you, #{current_user.name || current_user.email}. You have been upgraded to a Premium membership."
            redirect_to wikis_path(current_user)
        end
        
        rescue Stripe::CardError => e
            flash[:error] = e.message
            redirect_to new_charge_path
    end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
    
    def create
        params['users'].each do |id|
            @wiki = Wiki.find(params[:wiki_id])
            @collaborator = @wiki.collaborators.build(user_id: id)
    
            if @collaborator.save
                flash[:notice] = "Collaborators have been added to this wiki."
            else
                flash[:error] = "There was a problem adding collaborators to this wiki. Check to see if individuals have already been added."
            end
        end
        redirect_to edit_wiki_path(@wiki)
    end

    def destroy
        @wiki = Wiki.find(params[:wiki_id])
        @collaborator = Collaborator.find(params[:id])
 
        if @collaborator.destroy
            flash[:notice] = "Collaborator removed from wiki"
        else
            flash[:error] = "There was a problem removing the collaborator from the wiki. Please check spelling and try again."
        end
        redirect_to edit_wiki_path(@wiki)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def update
        current_user.update_attributes(role: "standard")
        current_user.publicize_wikis       
        
        flash[:alert] = "You have been downgraded to a Standard membership. Your private wikis can now be viewed publicly. "
        redirect_to wikis_path(current_user)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    @wikis = policy_scope(Wiki)
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Membership Upgrade",
      amount: 1500
    }
  end

  def new
    @wiki = Wiki.new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }", 
      description: "Membership Upgrade - #{current_user.name}",
      amount: 1500
    }
    authorize @wiki
  end
  
  def create
    @wiki = Wiki.new(wiki_params) 
    @wiki.user = current_user
    authorize @wiki
    if @wiki.save
      flash[:notice] = "Wiki successfully created!"
      redirect_to wikis_path
    else
      flash[:error] = "There was an error creating a new wiki. Please try again."
      render @wikis
    end
  end
    
  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end
  
  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    
    if @wiki.update_attributes(wiki_params)
      flash[:notice] = "Wiki was updated."
      redirect_to wikis_path
    else
      flash[:error] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end
  
  def destroy
    @wiki = Wiki.find(params[:id])
    
    if @wiki.destroy
      flash[:notice] = "Wiki deleted."
      redirect_to wikis_path
    else
      flash[:notice] = "There was an error deleting wiki. Please try again."
      render :destroy
    end
  end
    
  private
  
  def wiki_params
    (params.require(:wiki).permit(:title, :body, :private, :user_id))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def markdown_to_html(markdown)
        renderer = Redcarpet::Render::HTML.new
        extensions = {fenced_code_blocks: true}
        redcarpet = Redcarpet::Markdown.new(renderer, extensions)
        (redcarpet.render markdown).html_safe
    end
        
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/_charge.html.erb
      <%= form_tag charges_path do %>
          <h4>Upgrade to Premium!</h4>
          <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key= '<%= Rails.configuration.stripe[:publishable_key]%>'
              data-amount="<%= 1500 %>" data-description='<%= "Premium Membership" %>'> 
          </script>
      <% end %>

app/views/charges/new.html.erb
<% if current_user.role == 'standard' %>
    <%= form_tag charges_path do %>
        <h4>Upgrade to Premium!</h4>
        <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>"
            data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>"> 
        </script>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wiki Collaboration</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:900' rel='stylesheet' type='text/css'>
    <%= csrf_meta_tags %>
  
  </head>
  <body>
    <div class="col-md-12">
      <div class="row">
        <div class="col-md-3">
          <div class='heading-content'>
            <%= image_tag("collab.gif", :alt => "collaboration", :class => "img-heading") %>
            <h1 class="main-heading">Wiki Collaboration Tool</h1>
            <h4 class="heading-subtext">Create & Collaborate</h4>
          </div>
          <div class="navigation">
            <ul class="nav nav-pill nav-stacked">
              <li><%= link_to "Main Page", root_path %></li>
              <li><%= link_to "Wikis", wikis_path %></li>
            </ul>
          </div>
        </div>
  
        <div class="col-md-9">
          <div class="pull-right user-info">
            <% if current_user %>
              Hello <%= current_user.name || current_user.email %>! 
              <%= link_to  edit_user_registration_path, class: 'btn btn-primary btn-sm' do %>
                <span class= 'glyphicon glyphicon-user'></span>
              <% end %>
              <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-sm' do %>
                <span class= 'glyphicon glyphicon-log-out'></span>
              <% end %>
            <% else %>
              <%= link_to "Log In", new_user_session_path, class: 'btn btn-primary' %> 
              <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %>
            <% end %>
          </div>
          <div>
            <% if flash[:notice] %>
              <div class="alert alert-success">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <%= flash[:notice] %>
              </div>
            <% elsif flash[:error] %>
              <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <%= flash[:error] %>
              </div>
            <% elsif flash[:alert]%>
              <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <%= flash[:alert] %>
              </div>
            <% end %>
          </div>
         <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
<div>
   <h1 class="main-content">Wiki Collaboration Tool</h1>
   <h3> A production quality SaaS app that allows users to create and collaborate on wikis.</h3>
   <h4>♦ Users can  sign up for a free Standard account to create, edit, and delete public wikis.</h4>
   <h4>♦ Users can purchase a Premium account that allows them to create private wikis.</h4>
   <h4>♦ If User downgrades from Premium to Standard account, private wikis become public.</h4>
   <h4>♦ When collaborators are removed they are no longer able to view or work on private wikis.</h4>
   <h4>♦ Users can chose collaborators from a dropdown menu to work on privatewikis.</h4>
          

</div>

app/views/wikis/_form.html.erb
<div>
    <% if current_user.role == 'admin' || current_user.role == 'premium' %>
        <div class="form-group">
          <%= f.label :private, class: 'checkbox' do %>
          <%= f.check_box :private %> Private wiki
          <% end %>
        </div>
    <% end %>
</div>

app/views/wikis/edit.html.erb
<h1 class="main-content">Edit Wiki</h1>
<div class='row'>
    <div class='col-md-4'>
        <h4> Guidelines for Wikis </h4>
        <ul>
            <li> Make it informative</li>
            <li> Make it truthful </li>
        </ul><br>
        
        <h4>Current Collaborators:</h4>
         <ul class="collaborators_list">
                <% @wiki.collaborators.each do |collaborator| %>
                    <li><%= collaborator.user.name %> 
                    <small><%=link_to "  (delete)", wiki_collaborator_path(@wiki, collaborator.id), method: :delete %></small></li>
                <% end %>
        </ul><br> 

        <h4>Add Collaborators</h4>
        <%= form_tag wiki_collaborators_path(@wiki) do %>
            <% users_array = User.all.map { |user| [user.name, user.id]} %>
            <%= select_tag('users', options_for_select(users_array,:selected => params[:users]), multiple: true) %>    
            <%= submit_tag('Add', name: 'collaborators[submit]') %>
        <% end %>
    </div>
    
    <div class='col-md-8'>
        <%= form_for @wiki do |f| %>
            <div class="form-group">
                <%= f.label :title %>
                <%= f.text_field :title, class: 'form-control', placeholder: "Enter title" %>
            </div>
            <div class="form-group">
                <%= f.label :body %>
                <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter text" %>
            </div>
            <%= render partial: 'form', :locals => {:f => f} %>
            <div class="form-group">
                <%= f.submit "Save", class: 'btn btn-success' %>
            </div>
        <% end %>
    </div>
</div>

app/views/wikis/index.html.erb
<h1 class="main-content">All Wikis</h1>
<% if policy(Wiki.new).create? %>
    <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
<% end %>    
<% @wikis.each do |wiki| %>
    <div class="media">
        <div class="media-body">
            <h4 class="media-heading"><%= link_to wiki.title, wiki %>
            <small><% if wiki.private %> - Private Wiki<% end %>
            </small></h4>
        </div>
    </div>
<% end %>
<br>

app/views/wikis/new.html.erb
<h1 class="main-content">New Wiki</h1>
<div class='row'>
    <div class='col-md-4'>
        <p> Guidelines for Wikis </p>
        <ul>
            <li> Make it informative </li>
            <li> Make it fair </li>
        </ul>
    </div>
    <div class='col-md-6'>
        <%= form_for @wiki do |f| %>
            <div class="form-group">
                <%= f.label :title %>
                <%= f.text_field :title, class: 'form-control', placeholder: "Enter title" %>
            </div>
            <div class="form-group">
                <%= f.label :body %>
                <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter text" %>
            </div>
            <div class="form-group">
                <%= f.submit "Save", class: 'btn btn-success' %>
            </div>
            <%= render partial: 'form', :locals => {:f => f} %>
        <% end %><br>
        
        <% if current_user.role == 'standard' %>
            <%= form_tag charges_path do %>
                <h4> Create private Wikis and other options by upgrading to a <em>Premium</em> account. </h4>
                <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>"
                    data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>"> 
                </script>
            <% end %>
        <% end %>
        
    </div>
    <div class='col-md-2'></div>
</div>

app/views/wikis/show.html.erb
<h1 class="main-content"><%= markdown_to_html @wiki.title %></h1>

<% if policy(@wiki).edit? %>
    <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
<% end %>

<p><%= markdown_to_html @wiki.body %></p>

<% if policy(@wiki).destroy? %>
    <%= link_to "Delete", [@wiki], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %> 
<% end %><br>

<%if @user && current_user.role == 'standard' && @wiki.user == current_user %>
    <%= form_tag charges_path do %>
        <h5>Do you want to make this wiki private? Upgrade to a Premium membership for more options.</h5>
        <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>"
              data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>"> 
        </script>
    <% end %>
<% end %>